platform :ios, '7.0'
pod 'CocoaLumberjack'
pod 'Masonry'
pod ‘MBProgressHUD'
pod 'ReactiveCocoa'
pod 'AMapNavi'
pod 'AMapSearch'
pod 'JDStatusBarNotification'
pod 'SDWebImage'
pod 'AMapLocation'
pod 'M13ProgressSuite'
pod 'UMengAnalytics-NO-IDFA'
